name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: Ensure sqlite3
        run: |
          if ! command -v sqlite3 >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y sqlite3
          else
            sqlite3 --version
          fi
      - name: Run quality checks
        run: |
          uv python install 3.12
          uv sync --frozen
          make quality
